"""add_activity_actor_details

Revision ID: 2c0fbe0d2abc
Revises: 9df59819ad23
Create Date: 2026-03-16 16:20:42.548082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0fbe0d2abc'
down_revision: Union[str, Sequence[str], None] = '9df59819ad23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('actor', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('details', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('correlated_group_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_incidents_correlated_group_id'), 'incidents', ['correlated_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_correlated_group_id'), table_name='incidents')
    op.drop_column('incidents', 'correlated_group_id')
    op.drop_column('activities', 'details')
    op.drop_column('activities', 'actor')
    # ### end Alembic commands ###
