"""add_explanation_to_incidents

Revision ID: 95d7b36c23ac
Revises: a047dee65ab7
Create Date: 2026-03-16 19:05:25.429483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d7b36c23ac'
down_revision: Union[str, Sequence[str], None] = 'a047dee65ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('explanation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'explanation')
    # ### end Alembic commands ###
