"""add_recommended_action

Revision ID: 9df59819ad23
Revises: 6b17b9a8a3b7
Create Date: 2026-03-15 14:11:31.422277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df59819ad23'
down_revision: Union[str, Sequence[str], None] = '6b17b9a8a3b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('recommended_action', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'recommended_action')
    # ### end Alembic commands ###
