local   all             all                                     trust
host    all             all                                     md5
local   replication     all                                     trust
host    replication     all                                     md5
host    all             all                                     scram-sha-256
